package main

import (
	domain "github.com/udisondev/go-mapping-jam/domain"
	dto "github.com/udisondev/go-mapping-jam/dto"
	external "github.com/udisondev/go-mapping-jam/external"
	user "github.com/udisondev/go-mapping-jam/user"
)

// Code generated by go-mapping-jam. DO NOT EDIT.
type MapperImpl struct{}

func (m *MapperImpl) MapPersonToDomain(src dto.Person) domain.Person {
	target := domain.Person{}
	target.LastName = src.LastName
	target.MiddleName = src.MiddleName
	target.Age = src.Age
	target.Account = m.sybvxtabzzhfrqr(src.Account)
	target.Profile = m.axnponoqfhbqnuv(src.Profile)
	return target
}
func (m *MapperImpl) sybvxtabzzhfrqr(src external.Account) external.Account {
	target := external.Account{}
	target.Login = m.fxpvxqelsxedcif(src.Login)
	target.Password = src.Password
	return target
}
func (m *MapperImpl) fxpvxqelsxedcif(src user.Login) user.Login {
	target := user.Login{}
	target.Value = src.Value
	return target
}
func (m *MapperImpl) axnponoqfhbqnuv(src dto.Profile) domain.Profile {
	target := domain.Profile{}
	return target
}
func (m *MapperImpl) MapPersonToDTO(src domain.Person) dto.Person {
	target := dto.Person{}
	target.MiddleName = src.MiddleName
	target.Age = src.Age
	target.Account = m.sybvxtabzzhfrqr(src.Account)
	target.Profile = m.mwrhsiwryrfvlqa(src.Profile)
	target.FirstName = src.Firstname
	target.LastName = src.LastName
	return target
}
func (m *MapperImpl) mwrhsiwryrfvlqa(src domain.Profile) dto.Profile {
	target := dto.Profile{}
	target.Phone = src.Number
	return target
}
