package mapper

import (
	domain "github.com/udisondev/go-mapping-jam/domain"
	dto "github.com/udisondev/go-mapping-jam/dto"
	external "github.com/udisondev/go-mapping-jam/external"
	user "github.com/udisondev/go-mapping-jam/user"
)

// Code generated by go-mapping-jam. DO NOT EDIT.
type MapperImpl struct{}

func (m *MapperImpl) MapPersonToDTO(src domain.Person) dto.Person {
	target := dto.Person{}
	target.FirstName = firstNameMapper(src.Firstname)
	target.LastName = src.LastName
	target.MiddleName = src.MiddleName
	target.Age = src.Age
	target.Account = m.jcdpywqnpqhwsha(src.Account)
	target.Profile = m.slhgdbecuvpufzm(src.Profile)
	return target
}
func (m *MapperImpl) jcdpywqnpqhwsha(src external.Account) external.Account {
	target := external.Account{}
	target.Login = m.zfywnpptsapgesl(src.Login)
	target.Password = src.Password
	return target
}
func (m *MapperImpl) zfywnpptsapgesl(src user.Login) user.Login {
	target := user.Login{}
	target.Value = src.Value
	return target
}
func (m *MapperImpl) slhgdbecuvpufzm(src domain.Profile) dto.Profile {
	target := dto.Profile{}
	target.Phone = src.Number
	return target
}
func (m *MapperImpl) MapPersonToDomain(src dto.Person) domain.Person {
	target := domain.Person{}
	target.Profile = m.sszzserevegbqno(src.Profile)
	target.LastName = src.LastName
	target.MiddleName = src.MiddleName
	target.Age = src.Age
	target.Account = m.jcdpywqnpqhwsha(src.Account)
	return target
}
func (m *MapperImpl) sszzserevegbqno(src dto.Profile) domain.Profile {
	target := domain.Profile{}
	target.Number = src.Phone
	return target
}
